### ISSUE TITLE
Create a class for general number operations.

### ISSUE THREAD

**Issue by blackmathx** [bowebgit/ScientificJavaLibrary#5]
A class called IntegerFunctions can contain leastCommonMultiple, greatestCommonDiviser, and uniqueFactorization that returns an array. It should also contain functions such as boolean prime(), and int modular(int a, int modB).

**Comment by thisisagithubaccounta** [comment]
I agree about the separate class, i'm not sure about the name though. I can see this class growing in the future to contain more than just integer functions. I'd say just call it Math but then its going to be quite ugly when used in conjunction with java.lang.Math. What about MathUtils?
Also mod is a native java operator `a%b` = a modulo b

**Comment by blackmathx** [comment]
MathOperations, MathUtils, NumericalOperators? Any combination like MathOperators would do, if you would like to pick. Provide a modular function anyway for completeness.

**Comment by thisisagithubaccounta** [comment]
I'll have a crack at it now. I disagree with adding the mod function anyway, any use of it will be a less efficient version of the native implementation. It will also make the code in which its used longer.

**Comment by blackmathx** [comment]
The modular function is a wrapper method for the original implementation. Return the result of the native mod function. Some advantages are that the method can be expanded to include logging, throw custom exceptions, etc.

**Comment by thisisagithubaccounta** [comment]
I'm struggling to see a situation where this would be used. Native operators will throw there own exceptions, I think if anything a wrapper would make it more brittle. I think the initial version of this class is in master now, so this issue can be closed if your happy with it.
