### ISSUE TITLE
Fix the mode function in Statistics.java

### ISSUE THREAD

**Issue by bowebgit** [bowebgit/ScientificJavaLibrary#6]
The mode() function needs implemented in Statistics.java.

**Comment by NavarrePratt** [comment]
I'll work on this issue and implement mode()

**Comment by bowebgit** [comment]
Go ahead and return an array, which I think is better than returning a single valued Double. That way they can call the length function on the array if they already have it, but also write a modeCount() method because it is useful. The comment was a 3rd grade definition of mode, but these are great ideas. Have fun with it!

**Comment by NavarrePratt** [comment]
I submitted a pull request that implements this functionality along with tests for it.

**Comment by bowebgit** [comment]
Merged and closed.

**Comment by bowebgit** [comment]
@NavarrePratt Navarre please become a contributor to the project by responding to the request.
